export class ColorScheme {
  // Define color properties
  primary: string;
  onPrimary: string;
  primaryContainer: string;
  onPrimaryContainer: string;
  primaryFixed: string;
  onPrimaryFixed: string;
  primaryFixedDim: string;
  onPrimaryFixedVariant: string;
  secondary: string;
  onSecondary: string;
  secondaryContainer: string;
  onSecondaryContainer: string;
  secondaryFixed: string;
  onSecondaryFixed: string;
  secondaryFixedDim: string;
  onSecondaryFixedVariant: string;
  tertiary: string;
  onTertiary: string;
  tertiaryContainer: string;
  onTertiaryContainer: string;
  tertiaryFixed: string;
  onTertiaryFixed: string;
  tertiaryFixedDim: string;
  onTertiaryFixedVariant: string;
  error: string;
  onError: string;
  errorContainer: string;
  onErrorContainer: string;
  outline: string;
  surface: string;
  onSurface: string;
  onSurfaceVariant: string;
  inverseSurface: string;
  inverseOnSurface: string;
  inversePrimary: string;
  shadow: string;
  outlineVariant: string;
  scrim: string;
  surfaceContainerHighest: string;
  surfaceContainerHigh: string;
  surfaceContainer: string;
  surfaceContainerLow: string;
  surfaceContainerLowest: string;
  surfaceBright: string;
  surfaceDim: string;
  contrast: string;
  surfaceTint: string;

  constructor(theme: 'dark' | 'light') {
    if (theme === 'dark') {
      this.primary = '#80d5d4';
      this.onPrimary = '#003737';
      this.primaryContainer = '#004f50';
      this.onPrimaryContainer = '#9cf1f0';
      this.primaryFixed = '#9cf1f0';
      this.onPrimaryFixed = '#002020';
      this.primaryFixedDim = '#80d5d4';
      this.onPrimaryFixedVariant = '#004f50';
      this.secondary = '#b0cccb';
      this.onSecondary = '#1b3534';
      this.secondaryContainer = '#324b4b';
      this.onSecondaryContainer = '#cce8e7';
      this.secondaryFixed = '#cce8e7';
      this.onSecondaryFixed = '#051f1f';
      this.secondaryFixedDim = '#b0cccb';
      this.onSecondaryFixedVariant = '#324b4b';
      this.tertiary = '#b3c8e8';
      this.onTertiary = '#1c314b';
      this.tertiaryContainer = '#334863';
      this.onTertiaryContainer = '#d3e4ff';
      this.tertiaryFixed = '#d3e4ff';
      this.onTertiaryFixed = '#041c35';
      this.tertiaryFixedDim = '#b3c8e8';
      this.onTertiaryFixedVariant = '#334863';
      this.error = '#ffb4ab';
      this.onError = '#690005';
      this.errorContainer = '#93000a';
      this.onErrorContainer = '#ffdad6';
      this.outline = '#889392';
      this.surface = '#0e1514';
      this.onSurface = '#dde4e3';
      this.onSurfaceVariant = '#bec9c8';
      this.inverseSurface = '#dde4e3';
      this.inverseOnSurface = '#2b3231';
      this.inversePrimary = '#006a6a';
      this.shadow = '#000000';
      this.outlineVariant = '#3f4948';
      this.scrim = '#000000';
      this.surfaceContainerHighest = '#2f3636';
      this.surfaceContainerHigh = '#252b2b';
      this.surfaceContainer = '#1a2121';
      this.surfaceContainerLow = '#161d1d';
      this.surfaceContainerLowest = '#090f0f';
      this.surfaceBright = '#343a3a';
      this.surfaceDim = '#0e1514';
      this.contrast = '#ffffff';
      this.surfaceTint = '#80D5D4';
    } else {
      this.primary = '#006a6a';
      this.onPrimary = '#ffffff';
      this.primaryContainer = '#9cf1f0';
      this.onPrimaryContainer = '#002020';
      this.primaryFixed = '#9cf1f0';
      this.onPrimaryFixed = '#002020';
      this.primaryFixedDim = '#80d5d4';
      this.onPrimaryFixedVariant = '#004f50';
      this.secondary = '#4a6363';
      this.onSecondary = '#ffffff';
      this.secondaryContainer = '#cce8e7';
      this.onSecondaryContainer = '#051f1f';
      this.secondaryFixed = '#cce8e7';
      this.onSecondaryFixed = '#051f1f';
      this.secondaryFixedDim = '#b0cccb';
      this.onSecondaryFixedVariant = '#324b4b';
      this.tertiary = '#4b607c';
      this.onTertiary = '#ffffff';
      this.tertiaryContainer = '#d3e4ff';
      this.onTertiaryContainer = '#041c35';
      this.tertiaryFixed = '#d3e4ff';
      this.onTertiaryFixed = '#041c35';
      this.tertiaryFixedDim = '#b3c8e8';
      this.onTertiaryFixedVariant = '#334863';
      this.error = '#ba1a1a';
      this.onError = '#ffffff';
      this.errorContainer = '#ffdad6';
      this.onErrorContainer = '#410002';
      this.outline = '#6f7979';
      this.surface = '#f4fbfa';
      this.onSurface = '#161d1d';
      this.onSurfaceVariant = '#3f4948';
      this.inverseSurface = '#2b3231';
      this.inverseOnSurface = '#ecf2f1';
      this.inversePrimary = '#80d5d4';
      this.shadow = '#000000';
      this.outlineVariant = '#bec9c8';
      this.scrim = '#000000';
      this.surfaceContainerHighest = '#dde4e3';
      this.surfaceContainerHigh = '#e3e9e9';
      this.surfaceContainer = '#e9efee';
      this.surfaceContainerLow = '#eff5f4';
      this.surfaceContainerLowest = '#ffffff';
      this.surfaceBright = '#f4fbfa';
      this.surfaceDim = '#d5dbda';
      this.contrast = '#000000';
      this.surfaceTint = '#006A6A';
    }
  }
}
